#!/bin/bash

cd ./testFiles

display_menu()
{
	echo "--------------------------------------------------"
	echo "			Study guide APP"
	echo "--------------------------------------------------"
	echo "	A) Study an existing file?"
	echo "	B) Create a new study guide?"
	echo " 	C) List existing study guide files"
	echo "	D) Edit existing study guide File"
	echo "	Enter q or Q to quit the program"
}

studyExistingFile()
{
ls
array=(`ls`);
cd ..
echo "Which file would you like to study"
read file
i=0
j=0
for k in ${array[@]}
do
	j=$((j+1))
done
while [ $file != ${array[$i]} ] && [ $i -ne $((j-1)) ]
do
	i=$((i+1))
done
echo "$i	$j"
if [ $file != ${array[$i]} ] && [ $i -eq $((j-1)) ]
then
	echo "Not a file!"
else
	./studyGuide ./testFiles/${array[$i]}
fi
}

userMenuSelection()
{
	read user_answer
	user_answer=${user_answer^}
	while [ $user_answer != "Q" ]
	do
		case $user_answer in
			A) studyExistingFile;;
			B);;
			C);;
			D);;
			Q);;
			*) echo "Invalid option"
				display_menu
				read user_Anser
				user_answer=${user_answer^};;
		esac
	done
}

display_menu
userMenuSelection

